### ISSUE TITLE
Re-apply skb ride the rocket fix

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/sync-gateway-testcluster#23]
Here is the fix for the [skb rides the rocket](https://issues.couchbase.com/browse/MB-16640) issue:

```
# https://github.com/couchbase/sync_gateway/issues/1193#issuecomment-150395613
- hosts: tag_Type_couchbaseserver:tag_Type_syncgateway:tag_Type_gateload
  remote_user: centos
  any_errors_fatal: true
  sudo: true
  tasks:
  - name: disable scatter / gather for eth0 (see http://bit.ly/1R25bbE)
    shell: ethtool -K eth0 sg off
```
